- helm_deploy/hmpps-tier/templates/_envs.tpl
- src/main/resources/application-aws.yml
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
Pass values in from the kubernetes secrets
> Pass in the required values from existing kube secrets

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ChangeLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelCalculator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationServiceTest.kt
Move IOM Nomial from protect to change.
> Move IOM Nomial from protect to change.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ChangeLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/CommunityApiDataService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationServiceTest.kt
Rename a method and take the shorter function style
> Some Kotlin refactoring while writing the BDD

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/client/CommunityApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/MockedEndpointsTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/TierCalculationTest.kt
- src/test/resources/application-test.yml
there are no words
although there could be tests
> MAS-312 retrieve requirements using correct URL

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
values taken from court-case-service
> Preprod and Prod environment values 

- build.gradle.kts
fixes the gradle dependencyCheckAnalyze task which has been failing for a couple of days
> FIX-BUILD: New version of spring boot plugin

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/controller/TierCalculationRequiredEventListener.kt
Something small and temporary so we aren't overwhelmed by massive logs for each 404
> Logging: make 404s quieter

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/client/AssessmentApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/domain/enums/AssessmentComplexityFactor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/AssessmentApiDataService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/CommunityApiDataService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/domain/enums/AssessmentComplexityFactorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/ApiResponses.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/MockedEndpointsTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/AssessmentApiDataServiceTest.kt
- src/test/resources/fixtures/assessment-api/assessments.json
* Use assessment summary instead of latest assessment endpoint
* pass the section for the question answers
> Update our interactions with Assessment-API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/config/TelemetryConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TelemetryEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TelemetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TelemetryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationServiceTest.kt
Added App Insights TelemetryClient Bean and Configuration
Added custom business events for TierChanged and TierUnchanged
> 📈 MAS-353 Added telemetry events 

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/MandateForChange.kt
One day MandateForChange will be readable
> Null checks removed

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/MandateForChangeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/BddSteps.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/setup/MockedEndpointsTestBase.kt
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/IOM.8.6.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/MAPPA.6.7.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/OGRS.8.2.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/ROSHandRSRRule.6.5.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/additionalFactorsFemaleBreachRecall.6.11.1.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/additionalFactorsFemaleComplexity.6.11.2.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/additionalFactorsFemaleSentenceLength.6.11.4.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/additionalFactorsFemaleViolenceArson.6.11.3.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/additionalFactorsMaleAndFemale.6.9.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/assessAndProtectAxis.7.1.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/calculateROSHScore.6.4.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/calculateRSRScore.6.2.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/changeTierThresholds.10.1.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/criminogenicNeeds.8.4.feature
- src/test/resources/uk/gov/justice/digital/hmpps/hmppstier/integration/bdd/mandateForChange.9.5.feature
Also use int arguments where possible
> Remove duplicate Mandate For Change tests

- applicationinsights.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/client/AssessmentApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/client/CommunityApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/controller/TierCalculationRequiredEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/controller/advice/ControllerAdvice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/AssessmentApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ChangeLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/MandateForChange.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationService.kt
- src/main/resources/application.yml
Reduce some logging
Raise the log level going to App insights
> Remove some logging

- applicationinsights.json
TODO:  Revert once we're done unless we can prove it has 0 effect on our charts
> enable sampling for the preprod run

- build.gradle.kts
Finally got this working after much faffing. 
The integration and cucumber tests alone cover 72% of branch and 76% of complexity
> BUILD: include cucumber tests in coverage

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/AdditionalFactorsForWomen.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/TierCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/ProtectTierATest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/integration/setup/MockedEndpointsTestBaseVersionTwo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelCalculatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppstier/service/ProtectLevelThreeCalculatorTest.kt
- src/test/resources/application-test-version-two.yml
Work in progress
It is tricky to run two different versions of the application
> Mas 422 l3

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This reverts commit 22770ed364d27d0ed7c264f49652dd22a12dc058.
> MAS-444: Revert "Use helm reuse feature for own url"

- Dockerfile
Tested here: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-tier/3047/workflows/1225eb65-0699-4700-8127-a2a29ad559dd/jobs/7891
> Build Docker images using Java 17

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- helm_deploy/hmpps-tier/Chart.lock
- helm_deploy/hmpps-tier/Chart.yaml
> Update all non major dependencies (except Kotlin)

- helm_deploy/hmpps-tier/Chart.yaml
- helm_deploy/hmpps-tier/values.yaml
- helm_deploy/values-dev.yaml
Depends on https://github.com/ministryofjustice/hmpps-helm-charts/pull/143
> PI-2019 Update schedule for CP testing

- build.gradle.kts
To test changes to SQS library for distributed tracing
> PI-2342 Bump hmpps-sqs-spring-boot-starter to 4.1.0-beta

- helm_deploy/hmpps-tier/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This is now handled by the probation-integration DLQ redrive service
> PI-2317 Remove DLQ retry

- .circleci/config.yml
- build.gradle.kts
Also bump Cucumber version to 7.20.1
> PI-2713 Remove OWASP check in favour of Trivy scan
